# Generated by Django 3.2.23 on 2024-01-31 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='dni',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
