# Generated by Django 3.2.23 on 2024-01-30 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='proveedor.proveedor'),
        ),
    ]
