# Generated by Django 3.2.23 on 2024-02-11 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_producto_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marca',
            name='id',
        ),
        migrations.AddField(
            model_name='marca',
            name='idMarca',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
