# Generated by Django 3.2.23 on 2024-02-11 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_auto_20240211_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='nombre',
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo',
            field=models.CharField(default='', max_length=100, verbose_name='Tipo'),
            preserve_default=False,
        ),
    ]
